// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfmHVs_Nm8Sf5gH5ZJCCue1hycDrcLtlU',
    appId: '1:908487905308:web:5735d9c9bd2475aea10fd9',
    messagingSenderId: '908487905308',
    projectId: 'notes-pr-66cbe',
    authDomain: 'notes-pr-66cbe.firebaseapp.com',
    storageBucket: 'notes-pr-66cbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfqu88QiV7zAoHCzPS5SXCjZgQaW4TDYI',
    appId: '1:908487905308:android:1fc057c63e31affca10fd9',
    messagingSenderId: '908487905308',
    projectId: 'notes-pr-66cbe',
    storageBucket: 'notes-pr-66cbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcOFA57K3kLmB6wUHiN1yC_WbUM-1oD7U',
    appId: '1:908487905308:ios:850d45296e0e8ae0a10fd9',
    messagingSenderId: '908487905308',
    projectId: 'notes-pr-66cbe',
    storageBucket: 'notes-pr-66cbe.firebasestorage.app',
    iosBundleId: 'com.example.notesPr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcOFA57K3kLmB6wUHiN1yC_WbUM-1oD7U',
    appId: '1:908487905308:ios:850d45296e0e8ae0a10fd9',
    messagingSenderId: '908487905308',
    projectId: 'notes-pr-66cbe',
    storageBucket: 'notes-pr-66cbe.firebasestorage.app',
    iosBundleId: 'com.example.notesPr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfmHVs_Nm8Sf5gH5ZJCCue1hycDrcLtlU',
    appId: '1:908487905308:web:196dba9f1748c306a10fd9',
    messagingSenderId: '908487905308',
    projectId: 'notes-pr-66cbe',
    authDomain: 'notes-pr-66cbe.firebaseapp.com',
    storageBucket: 'notes-pr-66cbe.firebasestorage.app',
  );
}
